import { Award, BarChart3, ChevronRight, Dumbbell, UserRound } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { AchievementCard, AppHeader, EmptyState, ExerciseCard, LevelBadge, MetricCard, PageContainer, PrimaryButton, ProgressBar, ScoreGauge, SectionHeader, Wordmark, WorkoutCard } from './components';
import { activeExercise, demoUser, nextAchievement, scoreCategories, todayWorkout } from './data/demo';
import { useI18n } from './i18n';

export function Splash() { const nav=useNavigate(); const {t}=useI18n(); return <PageContainer className="splash"><div className="splash-glow"/><Wordmark institutional/><div className="splash-visual"><div className="athlete-silhouette"/><div className="motion-line l1"/><div className="motion-line l2"/></div><div className="splash-copy"><h1>{t('splash.line1')}<br/>{t('splash.line2')}<br/><em>{t('splash.line3')}</em></h1><div className="dots"><i/><i/><i/></div><PrimaryButton onClick={()=>nav('/onboarding')}>{t('common.start')} <span>→</span></PrimaryButton></div></PageContainer> }
export function Onboarding() { const nav=useNavigate(); return <PageContainer className="onboarding"><AppHeader/><div className="onboard-center"><div className="orbit"><Dumbbell/></div><div className="eyebrow">KALIX SYSTEM</div><h1>Construa força.<br/>Domine seu corpo.</h1><p>Uma jornada de progressão criada para o seu nível.</p></div><PrimaryButton onClick={()=>nav('/today')}>ENTRAR NO KALIX <span>→</span></PrimaryButton></PageContainer> }
export function Today() { const nav=useNavigate(); const {t}=useI18n(); return <PageContainer><AppHeader action={<button className="avatar" onClick={()=>nav('/profile')}>A</button>}/><section className="hero-copy"><span>22 SET • HOJE</span><h1>{t('dashboard.greeting',{name:demoUser.name})}</h1><p>{t('dashboard.subtitle')}</p></section><div className="metrics-grid"><MetricCard label={t('score.title')} value={demoUser.kalixScore} detail={t('score.delta',{value:demoUser.previousScoreDelta})} onClick={()=>nav('/score')}/><MetricCard label={t('streak.title')} value={`0${demoUser.streakDays}`} detail={t('streak.days',{value:demoUser.streakDays})}/></div><WorkoutCard title={todayWorkout.title.toUpperCase()} meta={`${todayWorkout.durationMinutes} MIN  •  ${todayWorkout.exerciseCount} EXERCÍCIOS`} onStart={()=>nav('/workout/demo')}/><SectionHeader title={t('dashboard.nextAchievement')} action={<button className="text-button" onClick={()=>nav('/progress')}>VER TODAS <ChevronRight/></button>}/><AchievementCard title={nextAchievement.title.toUpperCase()} current={nextAchievement.current} target={nextAchievement.target}/></PageContainer> }
export function Score() { const {t}=useI18n(); return <PageContainer className="score-page"><AppHeader title={t('score.title')} back/><section className="score-hero"><div className="eyebrow">{t('score.title')}</div><ScoreGauge value={demoUser.kalixScore}/><div className="score-delta">↗ {t('score.delta',{value:demoUser.previousScoreDelta})}</div><LevelBadge>FOUNDATION II</LevelBadge></section><section className="breakdown"><SectionHeader title="BREAKDOWN"/><div className="score-list">{scoreCategories.map(item=><div className="score-row" key={item.id}><div><span>{item.label}</span><strong>{item.value}</strong></div><ProgressBar value={item.value} max={250}/></div>)}</div></section></PageContainer> }
export function WorkoutFocus() { const nav=useNavigate(); const {t}=useI18n(); return <PageContainer className="focus-page"><header className="focus-header"><button className="icon-button" onClick={()=>nav('/today')}>×</button><div><strong>{todayWorkout.title.toUpperCase()}</strong><span>{t('workout.exercise',{current:2,total:7})}</span></div><button className="more">•••</button></header><ProgressBar value={2} max={7}/><section className="exercise-heading"><div className="eyebrow">EXERCÍCIO ATUAL</div><h1>{activeExercise.name}</h1></section><ExerciseCard><div className="exercise-stage"><div className="exercise-figure"><i/><b/><span/></div><div className="stage-floor"/></div></ExerciseCard><div className="set-data"><div><strong>{activeExercise.reps}</strong><span>REPS</span></div><i/><div><strong>2</strong><span>/ {activeExercise.sets} SÉRIES</span></div></div><PrimaryButton onClick={()=>{}}>{t('workout.finishSet')} <span>✓</span></PrimaryButton><div className="rest"><span>{t('workout.rest')}</span><strong>00:58</strong></div></PageContainer> }
const placeholders = {
  train:{titleKey:'placeholder.train.title',textKey:'placeholder.train.text',icon:Dumbbell},skills:{titleKey:'placeholder.skills.title',textKey:'placeholder.skills.text',icon:Award},progress:{titleKey:'placeholder.progress.title',textKey:'placeholder.progress.text',icon:BarChart3},profile:{titleKey:'placeholder.profile.title',textKey:'placeholder.profile.text',icon:UserRound},
} as const;
export function Placeholder({kind}:{kind:keyof typeof placeholders}) { const {t}=useI18n(); const item=placeholders[kind]; return <PageContainer><AppHeader/><EmptyState title={t(item.titleKey)} text={t(item.textKey)} icon={item.icon}/></PageContainer> }
